function postprocess_pareto_eq(matfile)

    if nargin < 1
        matfile = 'lambda_sweep_eq.mat';
    end

    fs = 10; % font size for plots

    S = load(matfile, 'sweep');
    sweep = S.sweep;

    lambda = sweep.lambda_list(:);
    phi_d  = sweep.phi_data(:);
    phi_p  = sweep.phi_pen(:);
    idx    = sweep.idx_corner;

    % ----------------------------
    % Pareto / L-curve
    % ----------------------------
    fig = figure('Color','w', 'Units','centimeters', 'Position',[2,2,8,6]);

    % grey color for curve, red for selected point
    col_curve   = [0.30 0.30 0.30];
    col_select  = [0.80 0.10 0.10];
    ms_curve    = 2; % 4.5
    ms_select   = 5; % 6.0
    lw_curve    = 1.2;

    loglog(phi_d, phi_p, '-o', ...
        'LineWidth', lw_curve, ...
        'MarkerSize', ms_curve, ...
        'Color', col_curve, ...
        'MarkerFaceColor', 'w', ...
        'MarkerEdgeColor', col_curve);
    hold on;

    loglog(phi_d(idx), phi_p(idx), 'o', ...
        'MarkerSize', ms_select, ...
        'LineWidth', 0.9, ...
        'Color', col_select, ...
        'MarkerFaceColor', col_select, ...
        'MarkerEdgeColor', col_select);


    set(gca, ...
        'FontSize', fs, ...
        'FontName', 'Times New Roman', ...
        'LineWidth', 0.7, ...
        'TickDir', 'out', ...
        'Box', 'on', ...
        'XMinorGrid', 'on', ...
        'YMinorGrid', 'on', ...
        'GridAlpha', 0.18, ...
        'MinorGridAlpha', 0.10);
    grid(gca,'on');

    exportgraphics(fig, 'pareto_curve_eq.pdf', 'ContentType', 'vector');


    % ----------------------------
    % Components vs lambda
    % ----------------------------
    fig = figure('Color','w', 'Units','centimeters', 'Position',[2,2,8,6]);

    col_data   = [0.00 0.35 0.70];
    col_pen    = [0.85 0.45 0.10];
    col_select = [0.80 0.10 0.10];

    ms_data    = 2.2; % 4.2
    ms_pen     = 2.2; % 4.2
    ms_select  = 5.8;
    lw_comp    = 1.2;

    yyaxis left
    h1 = loglog(lambda, phi_d, '-o', ...
        'LineWidth', lw_comp, ...
        'MarkerSize', ms_data, ...
        'Color', col_data, ...
        'MarkerFaceColor', 'w', ...
        'MarkerEdgeColor', col_data);
    hold on;
    loglog(lambda(idx), phi_d(idx), 'o', ...
        'MarkerSize', ms_select, ...
        'LineWidth', 0.9, ...
        'Color', col_select, ...
        'MarkerFaceColor', col_select, ...
        'MarkerEdgeColor', col_select);

    

    yyaxis right
    h2 = loglog(lambda, phi_p, '-s', ...
        'LineWidth', lw_comp, ...
        'MarkerSize', ms_pen, ...
        'Color', col_pen, ...
        'MarkerFaceColor', 'w', ...
        'MarkerEdgeColor', col_pen);
    hold on;
    loglog(lambda(idx), phi_p(idx), 'o', ...
        'MarkerSize', ms_select, ...
        'LineWidth', 0.9, ...
        'Color', col_select, ...
        'MarkerFaceColor', col_select, ...
        'MarkerEdgeColor', col_select);

    set(gca, ...
        'FontSize', fs, ...
        'FontName', 'Times New Roman', ...
        'LineWidth', 0.7, ...
        'TickDir', 'out', ...
        'Box', 'on', ...
        'XMinorGrid', 'on', ...
        'YMinorGrid', 'on', ...
        'GridAlpha', 0.18, ...
        'MinorGridAlpha', 0.10);

    grid(gca,'on');

    exportgraphics(fig, 'pareto_components_eq.pdf', 'ContentType', 'vector');
end